### ISSUE TITLE
Markdown files are a bit orangey

### ISSUE THREAD

**Issue by abose** [ArunyaGoojar/Easy-Eye-Dark-Brackets-Theme#4]
* open any markdown file
* The orange colors on headings look fine to me, but the main thing I note is orange color on bullet/numbered points in markdown.
* See the color theme below, not in line with the easy theme for other files.
![image](https://user-images.githubusercontent.com/5336369/212607564-72b90cea-adbb-4631-9504-027efa2b20ce.png)

**Comment by mathewdennis1** [comment]
maybe some tweaking here could help --> https://github.com/ArunyaGoojar/Easy-Eye-Dark-Brackets-Theme/blob/b4a007bc0307548b9b6b8c79a6289ce93c6f1b11/Easy-Eye-Dark.css#L23
